version: '3.8'
services:
    app:
        build: docker/app/new
        container_name: test-app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/app/xdebug.ini:/etc/php7/conf.d/xdebug.ini
            - ./:/var/www/html
        ports:
            - 8886:80
            - 9000
        working_dir: /var/www/html
        environment:
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        env_file: .env

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
